source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CheckmarkSegmentedControl_Example' do
  pod 'CheckmarkSegmentedControl', :path => '../'

  target 'CheckmarkSegmentedControl_Tests' do
    inherit! :search_paths
    pod 'Nimble', '~> 5.0'
  end
end
