source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CheckmarkSegmentedControl_Example', :exclusive => true do
  pod "CheckmarkSegmentedControl", :path => "../"
end

target 'CheckmarkSegmentedControl_Tests', :exclusive => true do
  pod "CheckmarkSegmentedControl", :path => "../"
  pod "Nimble", '~> 2.0.0-rc.3' 
  
end
