source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CheckmarkSegmentedControl_Example', :exclusive => true do
  pod "CheckmarkSegmentedControl", :path => "../"
end

target 'CheckmarkSegmentedControl_Tests', :exclusive => true do
  pod "CheckmarkSegmentedControl", :path => "../"
  pod 'Nimble', '~> 4.0'
  
end
